package class_attendance;

import Admin.admin_portal;
import Teacher.TeacherPortal;
import extrasource.staffData;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class Welcomepage extends javax.swing.JFrame {

    private String dbAnswer = null;
    String emailpattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    int randomCode;
    Connection conn=null;
    PreparedStatement pst=null;
    Statement smt=null;
    ResultSet rst=null;  
    String username = "root";
    String password = "shellbt31_ofis";    
    String serverurl = "jdbc:mysql://localhost:3306/facerecognitionattendance";
    String timezone = "?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";
    
    
    public Welcomepage() {
        initComponents();
        search_btn.setEnabled(false);
        resetpwd_btn.setEnabled(false);
        securityQuestion_combo1.setEditable(false);
    }
    
    private void resetData_signup() 
    {
        firstnamesignup_text.setText("");
        lastnamesignup_text.setText("");
        statussignup_combo.setSelectedItem("---");
        emailaddresssignup_text.setText("");
        mobilephonesignup_text.setText("");
        usernamesignup_text.setText("");
        passwordsignup_password.setText("");
        securityQuestion_combo.setSelectedItem("---");
        answerques_txt.setText("");
    }   
    
    private void resetData_forgetpwd(){
        emailaddressforget_text.setText("");
        securityQuestion_combo1.setSelectedItem("---");
        answerques_txt1.setText("");
        newpwd.setText("");
        emailaddressforget_text.setEditable(true);
        search_btn.setEnabled(false);
        resetpwd_btn.setEnabled(false);
    }
    
    public boolean checkusername(String Name)
    {
        boolean checkUser = false;
        
        try 
        {
            String query = "SELECT * FROM `useraccount` WHERE `Username` ='" + usernamesignup_text.getText()+ "'";            
            conn = DriverManager.getConnection(serverurl+timezone,username,password);
            pst = conn.prepareStatement(query);                    
            rst = pst.executeQuery();
            
            if(rst.next())
            {
                checkUser = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);
        }
         return checkUser;
    }
    
    public void validateEmail_forget(){
        String email_forgetpwd = emailaddressforget_text.getText();
        if(email_forgetpwd.matches(emailpattern)){
            search_btn.setEnabled(true);
        }else{
            search_btn.setEnabled(false);
        }
    }
    
    public void validateFields_forget(){
        String newpwd_forgetpwd = newpwd.getText();
        String securityquestion = securityQuestion_combo1.getSelectedItem().toString();
        String answer_forgetpwd = answerques_txt1.getText();
        if(!newpwd_forgetpwd.equals("")&& !securityquestion.equals("") && !answer_forgetpwd.equals("")){
            resetpwd_btn.setEnabled(true);
        }else{
            resetpwd_btn.setEnabled(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sign_tab = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        cancelsignin_button = new javax.swing.JButton();
        signin_button1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        usernamesignin_text = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        passwordsignin_password = new javax.swing.JPasswordField();
        showtextsignin_check = new javax.swing.JCheckBox();
        error_label = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lastnamesignup_text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        emailaddresssignup_text = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mobilephonesignup_text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        usernamesignup_text = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passwordsignup_password = new javax.swing.JPasswordField();
        cancelsignup_button = new javax.swing.JButton();
        signup_button = new javax.swing.JButton();
        showtextsignup_check = new javax.swing.JCheckBox();
        firstnamesignup_text = new javax.swing.JTextField();
        statussignup_combo = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        securityQuestion_combo = new javax.swing.JComboBox<>();
        answerques_txt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        emailaddressforget_text = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        securityQuestion_combo1 = new javax.swing.JComboBox<>();
        answerques_txt1 = new javax.swing.JTextField();
        newpwd = new javax.swing.JPasswordField();
        showtextforgetpwd_check = new javax.swing.JCheckBox();
        cancelforgetpwd_btn = new javax.swing.JButton();
        resetpwd_btn = new javax.swing.JButton();
        search_btn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Class Attendance");
        setBackground(new java.awt.Color(204, 204, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        sign_tab.setBackground(new java.awt.Color(204, 204, 204));
        sign_tab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        cancelsignin_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelsignin_button.setText("Cancel");
        cancelsignin_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelsignin_buttonActionPerformed(evt);
            }
        });

        signin_button1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signin_button1.setText("Sign In");
        signin_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signin_button1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Username: ");

        jLabel9.setText("Password: ");

        showtextsignin_check.setText("Show Text");
        showtextsignin_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showtextsignin_checkActionPerformed(evt);
            }
        });

        error_label.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        error_label.setForeground(new java.awt.Color(255, 0, 0));
        error_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(cancelsignin_button, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(signin_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordsignin_password, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernamesignin_text, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(showtextsignin_check)))
                .addGap(29, 29, 29))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(error_label, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(usernamesignin_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(passwordsignin_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(showtextsignin_check)))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelsignin_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signin_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(error_label, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        sign_tab.addTab("SIGN IN", jPanel3);

        jLabel1.setText("First Name             : ");

        jLabel2.setText("Last Name             : ");

        jLabel3.setText("Status                     : ");

        jLabel6.setText("Email address        : ");

        jLabel7.setText("Mobile Phone       :");

        jLabel4.setText("Username              : ");

        jLabel5.setText("Password               : ");

        cancelsignup_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelsignup_button.setText("Cancel");
        cancelsignup_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelsignup_buttonActionPerformed(evt);
            }
        });

        signup_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signup_button.setText("Sign Up");
        signup_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_buttonActionPerformed(evt);
            }
        });

        showtextsignup_check.setText("Show Text");
        showtextsignup_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showtextsignup_checkActionPerformed(evt);
            }
        });

        statussignup_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Staff", "Teacher" }));

        jLabel18.setText("Security Question : ");

        jLabel19.setText("Answer                   : ");

        securityQuestion_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "When your birthday date?", "What your first name pet?", "Where you favourite place to travel?" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailaddresssignup_text)
                    .addComponent(mobilephonesignup_text)
                    .addComponent(usernamesignup_text)
                    .addComponent(statussignup_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstnamesignup_text)
                    .addComponent(lastnamesignup_text)
                    .addComponent(securityQuestion_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answerques_txt)
                    .addComponent(passwordsignup_password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showtextsignup_check)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelsignup_button, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(signup_button, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnamesignup_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnamesignup_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statussignup_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailaddresssignup_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobilephonesignup_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernamesignup_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordsignup_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showtextsignup_check))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(securityQuestion_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answerques_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelsignup_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signup_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        sign_tab.addTab("SIGN UP", jPanel2);

        jLabel10.setText("Email Address       : ");

        emailaddressforget_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailaddressforget_textActionPerformed(evt);
            }
        });
        emailaddressforget_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailaddressforget_textKeyPressed(evt);
            }
        });

        jLabel15.setText("Security Question :");

        jLabel16.setText("Answer                   :");

        jLabel17.setText("New Password      :");

        securityQuestion_combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "When your birthday date?", "What your first name pet?", "Where you favourite place to travel?" }));

        newpwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newpwdKeyPressed(evt);
            }
        });

        showtextforgetpwd_check.setText("Show Text");
        showtextforgetpwd_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showtextforgetpwd_checkActionPerformed(evt);
            }
        });

        cancelforgetpwd_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelforgetpwd_btn.setText("Cancel");
        cancelforgetpwd_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelforgetpwd_btnActionPerformed(evt);
            }
        });

        resetpwd_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resetpwd_btn.setText("Reset Password");
        resetpwd_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetpwd_btnActionPerformed(evt);
            }
        });

        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(securityQuestion_combo1, javax.swing.GroupLayout.Alignment.LEADING, 0, 202, Short.MAX_VALUE)
                            .addComponent(answerques_txt1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newpwd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailaddressforget_text))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(showtextforgetpwd_check)
                            .addComponent(search_btn)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(cancelforgetpwd_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(resetpwd_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(emailaddressforget_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_btn))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(securityQuestion_combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(answerques_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(newpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showtextforgetpwd_check))
                .addGap(59, 59, 59)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelforgetpwd_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetpwd_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        sign_tab.addTab("Forget Password", jPanel4);

        jLabel12.setFont(new java.awt.Font("Kristen ITC", 3, 45)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Class Attendance Using");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel14.setFont(new java.awt.Font("Kristen ITC", 3, 45)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Real-Time Face Recognition");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extrasource/544E92.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(sign_tab, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sign_tab, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelsignin_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelsignin_buttonActionPerformed
        usernamesignin_text.setText("");
        passwordsignin_password.setText("");
        error_label.setText("");
    }//GEN-LAST:event_cancelsignin_buttonActionPerformed

    private void signin_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signin_button1ActionPerformed
        String username1 = usernamesignin_text.getText();
        String Password1 = passwordsignin_password.getText();

        try
        {
            String query = "SELECT * FROM `useraccount` WHERE `Username`=? and `Password`=?;";
            conn = DriverManager.getConnection(serverurl+timezone,username,password);
            pst = conn.prepareStatement(query);

            pst.setString(1, username1);
            pst.setString(2, Password1);
            rst = pst.executeQuery();

            if (rst.next())
            {
                String Status = rst.getString("Status");
                String Username1 = rst.getString("Username");
                String UserID = rst.getString("UserID");

                //admin
                if(Status.equals("Admin"))
                {
                    admin_portal admin = new admin_portal();
                    admin.setVisible(true);
                    this.setVisible(false);
                    this.dispose();
                }
                else
                {
                    error_label.setText("Please enter valid Username or Password or may check your portal");
                }

                //teacher
                if(Status.equals("Teacher"))
                {
                    TeacherPortal teacher = new TeacherPortal();
                    teacher.setVisible(true);
                    this.setVisible(false);
                    this.dispose();
                }

                //staff
                if(Status.equals("Staff"))
                {
                    TeacherPortal teacher = new TeacherPortal();
                    teacher.setVisible(true);
                    this.setVisible(false);
                    this.dispose();
                }

                else
                {
                    error_label.setText("Please enter valid Username or Password or may check your portal");
                }
            }
            else
            {
                error_label.setText("PLESE ENTER VALID USERID OR PASSWORD");
            }
        }
        catch(SQLException ex)
        {
            Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_signin_button1ActionPerformed

    private void showtextsignin_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showtextsignin_checkActionPerformed
        if(showtextsignin_check.isSelected())
        {
            passwordsignin_password.setEchoChar((char)0);
        }
        else
        {
            passwordsignin_password.setEchoChar('*');
        }
    }//GEN-LAST:event_showtextsignin_checkActionPerformed

    private void cancelsignup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelsignup_buttonActionPerformed
        resetData_signup();
    }//GEN-LAST:event_cancelsignup_buttonActionPerformed

    private void signup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_buttonActionPerformed
        String fname = firstnamesignup_text.getText();
        String lname = lastnamesignup_text.getText();
        String status = statussignup_combo.getSelectedItem().toString();
        String email = emailaddresssignup_text.getText();
        String mobilephone = mobilephonesignup_text.getText();
        String username1 = usernamesignup_text.getText();
        String  password1 = String.valueOf(passwordsignup_password.getPassword());
        String securityquestion = securityQuestion_combo.getSelectedItem().toString();
        String securityanswer = answerques_txt.getText();

        if(fname.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Add First Name");
        }
        else if(lname.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Add an Last Name");
        }
        else if(status.equals("---"))
        {
            JOptionPane.showMessageDialog(null, "Please choose your status");
        }
        else if(email.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Add a Email Address");
        }
        else if (!Pattern.matches(emailpattern, emailaddresssignup_text.getText()))
        {
            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(mobilephone.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Add a Mobile Phone");
        }
        else if(mobilephone.length()<11)
        {
            JOptionPane.showMessageDialog(null, "Your Mobile Phone must be '012-3456789'");
        }
        else if(username1.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Add a Username");
        }
        else if (checkusername(username1))
        {
            JOptionPane.showMessageDialog(null, "This username Already Exist");
        }
        else if(password1.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Add a Password");
        }
        else if(password1.length()<3)
        {
            JOptionPane.showMessageDialog(null, "Your Password is Too Small");
        }
        else if(securityquestion.equals("---"))
        {
            JOptionPane.showMessageDialog(null, "Please choose your security question");
        }
        else if(securityanswer.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Add your security answer");
        }
        else
        {
            try
            {
                String query ="Insert into useraccount (FirstName,LastName,Status,Email,MobilePhone,Username,Password,SecurityQuestion,SecurityAnswer) values (?,?,?,?,?,?,?,?,?)";
                conn = DriverManager.getConnection(serverurl+timezone,username,password);
                pst = conn.prepareStatement(query);
                pst.setString(1, fname);
                pst.setString(2, lname);
                pst.setString(3, status);
                pst.setString(4, email);
                pst.setString(5, mobilephone);
                pst.setString(6, username1);
                pst.setString(7, password1);
                pst.setString(8, securityquestion);
                pst.setString(9, securityanswer);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "New User Add Successfully");
                resetData_signup();
            }
            catch (HeadlessException | SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_signup_buttonActionPerformed

    private void showtextsignup_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showtextsignup_checkActionPerformed
        if(showtextsignup_check.isSelected())
        {
            passwordsignup_password.setEchoChar((char)0);
        }
        else
        {
            passwordsignup_password.setEchoChar('*');
        }
    }//GEN-LAST:event_showtextsignup_checkActionPerformed

    private void showtextforgetpwd_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showtextforgetpwd_checkActionPerformed
        if(showtextforgetpwd_check.isSelected())
        {
            newpwd.setEchoChar((char)0);
        }
        else
        {
            newpwd.setEchoChar('*');
        }
    }//GEN-LAST:event_showtextforgetpwd_checkActionPerformed

    private void cancelforgetpwd_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelforgetpwd_btnActionPerformed
        resetData_forgetpwd();
    }//GEN-LAST:event_cancelforgetpwd_btnActionPerformed

    private void resetpwd_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetpwd_btnActionPerformed
        String answer = answerques_txt1.getText();
        String newpassword = newpwd.getText();
        if(answer.equals(dbAnswer)){
            try{
            String query = "UPDATE `useraccount` SET `Password`=? WHERE `Email`=?;";
            conn = DriverManager.getConnection(serverurl+timezone,username,password);
            pst = conn.prepareStatement(query);

            pst.setString(1, newpassword);
            pst.setString(2, emailaddressforget_text.getText());
            if (pst.executeUpdate() >0)
                {
                    JOptionPane.showMessageDialog(null, "Update Data Successfully");
                    resetData_forgetpwd();
                }
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(this,"Cannot Update Data");
            }            
        }else{
            JOptionPane.showMessageDialog(null, "Incorrect Answer","Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_resetpwd_btnActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        String email = emailaddressforget_text.getText();
        staffData user;
            
        try{
            String query = "SELECT * FROM `useraccount` WHERE `Email`=?;";
            conn = DriverManager.getConnection(serverurl+timezone,username,password);
            pst = conn.prepareStatement(query);

            pst.setString(1, email);
            rst = pst.executeQuery();
            
            if(rst.next())
            {
                user = new staffData();
                user.setSecurityQuestion(rst.getString("SecurityQuestion"));
                user.setSecurityAnswer(rst.getString("SecurityAnswer"));
                
                if(user == null)
                {
                   JOptionPane.showMessageDialog(this, "Incorrect Email","Message", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    search_btn.setEnabled(false);
                    emailaddressforget_text.setEditable(false);
                    dbAnswer = user.getSecurityAnswer();
                    securityQuestion_combo1.setSelectedItem(user.getSecurityQuestion());
                    validateFields_forget();
                }
            }
            else{
                 JOptionPane.showMessageDialog(null, "Incorrect Email","Message", JOptionPane.ERROR_MESSAGE);
                 search_btn.setEnabled(false);
            }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_search_btnActionPerformed

    private void emailaddressforget_textKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailaddressforget_textKeyPressed
        validateEmail_forget();
    }//GEN-LAST:event_emailaddressforget_textKeyPressed

    private void newpwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newpwdKeyPressed
        validateFields_forget();
    }//GEN-LAST:event_newpwdKeyPressed

    private void emailaddressforget_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailaddressforget_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailaddressforget_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerques_txt;
    private javax.swing.JTextField answerques_txt1;
    private javax.swing.JButton cancelforgetpwd_btn;
    private javax.swing.JButton cancelsignin_button;
    private javax.swing.JButton cancelsignup_button;
    private javax.swing.JTextField emailaddressforget_text;
    private javax.swing.JTextField emailaddresssignup_text;
    private javax.swing.JLabel error_label;
    private javax.swing.JTextField firstnamesignup_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField lastnamesignup_text;
    private javax.swing.JTextField mobilephonesignup_text;
    private javax.swing.JPasswordField newpwd;
    private javax.swing.JPasswordField passwordsignin_password;
    private javax.swing.JPasswordField passwordsignup_password;
    private javax.swing.JButton resetpwd_btn;
    private javax.swing.JButton search_btn;
    private javax.swing.JComboBox<String> securityQuestion_combo;
    private javax.swing.JComboBox<String> securityQuestion_combo1;
    private javax.swing.JCheckBox showtextforgetpwd_check;
    private javax.swing.JCheckBox showtextsignin_check;
    private javax.swing.JCheckBox showtextsignup_check;
    private javax.swing.JTabbedPane sign_tab;
    private javax.swing.JButton signin_button1;
    private javax.swing.JButton signup_button;
    private javax.swing.JComboBox<String> statussignup_combo;
    private javax.swing.JTextField usernamesignin_text;
    private javax.swing.JTextField usernamesignup_text;
    // End of variables declaration//GEN-END:variables
}
